import { existsSync, readFileSync } from 'fs';
import wrapMotoko, { type Motoko } from 'motoko/lib';
import { Module } from 'module';
import { basename, dirname, isAbsolute, join, resolve } from 'path';
import * as semver from 'semver';
import AstResolver from './ast';
import ImportResolver from './imports';
import { extractMocVersion, getMocJs } from './utils';
import { settings } from './globals';
import { Result, ok, err } from 'neverthrow';

type MocJsSource = 'bundled' | 'custom' | 'workspace';

type MocJsInfo = {
    version?: string;
    path: string;
    source: MocJsSource;
};

type Version = string | undefined;

// Hide version-dependent methods from direct access on motoko
type OptionalCompilerFunctions =
    | 'contextualDotModule'
    | 'contextualDotSuggestions'
    | 'checkWithScopeCache';
type PublicMotoko = Omit<Motoko, OptionalCompilerFunctions>;

/**
 * A Motoko compiler context.
 */
export class Context {
    public readonly uri: string;
    public readonly mocJsInfo: MocJsInfo;
    public readonly motoko: PublicMotoko;
    public readonly astResolver: AstResolver;
    public readonly importResolver: ImportResolver;

    public packages: [string, string][] | undefined;
    public error: string | undefined;
    public mopsArgs: string[] = [];

    // Optional compiler functions for backwards compatibility with older moc.js versions
    public readonly checkWithScopeCache:
        | Motoko['checkWithScopeCache']
        | undefined;
    public readonly contextualDotSuggestions:
        | Motoko['contextualDotSuggestions']
        | undefined;
    public readonly contextualDotModule:
        | Motoko['contextualDotModule']
        | undefined;

    constructor(uri: string, motoko: Motoko, mocJsInfo: MocJsInfo) {
        this.uri = uri;
        this.mocJsInfo = mocJsInfo;
        this.motoko = motoko;
        this.astResolver = new AstResolver(this);
        this.importResolver = new ImportResolver(this);

        const unavailable: OptionalCompilerFunctions[] = [];
        const has = (name: OptionalCompilerFunctions) => {
            const available = typeof motoko.compiler?.[name] === 'function';
            if (!available) unavailable.push(name);
            return available;
        };

        // Optional compiler functions for backwards compatibility with older moc.js versions
        this.checkWithScopeCache = has('checkWithScopeCache')
            ? motoko.checkWithScopeCache.bind(motoko)
            : undefined;
        this.contextualDotSuggestions = has('contextualDotSuggestions')
            ? motoko.contextualDotSuggestions.bind(motoko)
            : undefined;
        this.contextualDotModule = has('contextualDotModule')
            ? motoko.contextualDotModule.bind(motoko)
            : undefined;

        if (unavailable.length > 0) {
            console.info(
                `moc.js${
                    this.mocJsInfo.version ? ` (${this.mocJsInfo.version})` : ''
                } missing optional functions: ${unavailable.join(', ')}`,
            );
        }
    }

    applyMocFlags(userFlags: string[] | undefined) {
        const version = this.mocJsInfo.version;
        const validVersion = version && semver.valid(version);

        // moc < 1.2.0 crashes on invalid flags
        if (validVersion && semver.lt(validVersion, '1.2.0')) {
            if (this.mopsArgs.length || userFlags?.length) {
                console.warn(
                    `Motoko ${version} does not safely support extra flags (requires >= 1.2.0). Skipping user-defined flags to avoid crashes.`,
                );
            }
            return;
        }

        const flags: string[] = [...this.mopsArgs];
        if (userFlags?.length) {
            flags.push(...userFlags);
        }
        if (
            this.mocJsInfo.source === 'bundled' ||
            (validVersion && semver.gte(validVersion, '1.3.0-0'))
        ) {
            flags.push('--all-libs');
            console.log(`--all-libs moc flag: enabled`);
        } else {
            console.log(
                `--all-libs moc flag: disabled (requires >= 1.3.0, got ${version})`,
            );
        }
        if (!flags.length) {
            return;
        }
        try {
            this.motoko.setExtraFlags(flags);
        } catch {
            const supported: string[] = [];
            const unsupported: string[] = [];
            for (const flag of flags) {
                try {
                    this.motoko.setExtraFlags([flag]);
                    supported.push(flag);
                } catch {
                    unsupported.push(flag);
                }
            }
            if (unsupported.length) {
                console.warn('Skipping moc.js-unsupported flags:', unsupported);
            }
            this.motoko.setExtraFlags(supported);
        }
    }
}

const motokoPath = './motoko'; // Bundle generated by `esbuild`

// Path to the raw moc.min.js, shipped both for jest (src/server/compiler) and
// for the production extension (out/compiler, copied by `compile:motoko`).
// Used as the `MocJsInfo.path` for the bundled compiler so that isolated
// contexts can re-execute it via `Module._compile` for fresh `Flags` state.
const bundledMocJsPath = join(__dirname, 'compiler', 'moc-bundled.js');

// Compiler contexts (for workspaces with multiple Vessel directories)
const contexts: Context[] = [];

// Reuse `motoko` npm package instances to limit memory usage
const motokoInstances = new Map<string, [Motoko, MocJsInfo]>();

function getMotokoInstanceKey(
    uri: string,
    version: Version,
    workspaceRoot?: string,
    isolated?: boolean,
) {
    return `${uri}:${version || ''}:${settings?.mocJsPath || ''}:${
        workspaceRoot || ''
    }:${isolated ? 'isolated' : ''}`;
}

/**
 * Create or reuse a `moc.js` compiler instance.
 *
 * When `isolated` is true, the compiler is loaded via `Module._compile` so
 * each call returns an instance with its own internal `Flags` state — used
 * for canister entrypoints with per-canister flags (e.g. `--enhanced-migration`).
 */
async function requestMotokoInstance(
    uri: string,
    version: Version,
    workspaceRoot: string,
    isolated = false,
): Promise<[Motoko, MocJsInfo]> {
    const key = getMotokoInstanceKey(uri, version, workspaceRoot, isolated);
    const cached = motokoInstances.get(key);

    if (cached) {
        cached[0].clearPackages();
        return cached;
    }

    if (!isolated) {
        Object.keys(require.cache).forEach((key) => {
            if (
                key.endsWith('/out/motoko.js') ||
                key.endsWith('\\out\\motoko.js') ||
                key.includes('/out/compiler/') ||
                key.includes('\\out\\compiler\\')
            ) {
                delete require.cache[key];
            }
        });
    }

    const [motoko, mocJsInfo] = await createMotokoInstance(
        version,
        workspaceRoot,
        isolated,
    );

    configureMotokoCompiler(motoko);

    const instance: [Motoko, MocJsInfo] = [motoko, mocJsInfo];
    motokoInstances.set(key, instance);
    return instance;
}

function configureMotokoCompiler(motoko: Motoko) {
    motoko.compiler.setTypecheckerCombineSrcs?.(true);
    motoko.compiler.setBlobImportPlaceholders?.(true);
    motoko.setPublicMetadata([
        'candid:service',
        'candid:args',
        'motoko:stable-types',
    ]);
}

async function createMotokoInstance(
    version: Version,
    workspaceRoot: string,
    isolated = false,
): Promise<[Motoko, MocJsInfo]> {
    const configuredMocJsPath = settings.mocJsPath;
    if (configuredMocJsPath) {
        console.log('Trying to use custom moc.js path:', configuredMocJsPath);
        const resolvedPath = isAbsolute(configuredMocJsPath)
            ? configuredMocJsPath
            : resolve(workspaceRoot, configuredMocJsPath);
        const filename = basename(resolvedPath);
        const mocVersion = extractMocVersion(filename);

        if (existsSync(resolvedPath)) {
            const res = getCompiler(resolvedPath);
            if (res.isOk()) {
                const [compiler, path] = res.value;
                return [
                    wrapMotoko(compiler),
                    {
                        // assume that moc.js version in file name is correct, otherwise
                        // use provided version
                        version: mocVersion || version,
                        path,
                        source: 'custom',
                    },
                ];
            } else {
                // TODO: notify user via `connection.sendMessage()`
                console.error(
                    `Error loading custom moc.js from ${configuredMocJsPath}:`,
                    res.error.message,
                );
            }
        } else {
            // TODO: notify user via `connection.sendMessage()`
            console.warn(
                `Custom moc.js file not found at ${resolvedPath}, trying to download`,
            );
            if (mocVersion) {
                const res = await getMocJs(
                    mocVersion,
                    dirname(resolvedPath),
                ).andThen((path) => getCompiler(path));
                if (res.isOk()) {
                    const [compiler, path] = res.value;
                    return [
                        wrapMotoko(compiler),
                        {
                            version: mocVersion,
                            path,
                            source: 'custom',
                        },
                    ];
                } else {
                    console.error(
                        `Error while downloading custom moc.js to ${configuredMocJsPath}:`,
                        res.error.message,
                    );
                }
            }
        }
    }

    if (version) {
        const mocJsDir = join(__dirname, 'compiler');
        const res = await getMocJs(version, mocJsDir).andThen((path) =>
            getCompiler(path),
        );
        if (res.isOk()) {
            console.log('Using workspace moc.js version:', version);
            const [compiler, path] = res.value;
            return [
                wrapMotoko(compiler),
                {
                    version,
                    path,
                    source: 'workspace',
                },
            ];
        } else {
            console.warn(
                "Can't load moc.js for version",
                version,
                ':',
                res.error.message,
            );
        }
    }

    console.log('Falling back to bundled motoko package');

    if (isolated) {
        return [
            wrapMotoko(loadFreshCompiler(bundledMocJsPath)),
            { source: 'bundled', path: bundledMocJsPath },
        ];
    }
    return [
        require(motokoPath).default,
        { source: 'bundled', path: bundledMocJsPath },
    ];

    function getCompiler(path: string): Result<[any, string], Error> {
        try {
            const compiler = isolated
                ? loadFreshCompiler(path)
                : require(path).Motoko;
            if (!compiler) {
                return err(
                    new Error('Invalid moc.js file: missing Motoko export'),
                );
            }
            return ok([compiler, path]);
        } catch (error: any) {
            return err(
                error instanceof Error ? error : new Error(String(error)),
            );
        }
    }
}

let defaultContext: Context | undefined;
function requestDefaultContext() {
    if (!defaultContext) {
        const motoko = require(motokoPath).default;
        const mocJsInfo: MocJsInfo = {
            source: 'bundled',
            path: bundledMocJsPath,
        };
        configureMotokoCompiler(motoko);

        motokoInstances.set(getMotokoInstanceKey('', undefined), [
            motoko,
            mocJsInfo,
        ]);
        defaultContext = new Context('', motoko, mocJsInfo);
        insertContext(defaultContext);
    }
    return defaultContext;
}
requestDefaultContext(); // Always add a default context

/**
 * Reset all contexts (used to update Vessel configuration).
 */
export function resetContexts() {
    contexts.length = 0;
    if (defaultContext) {
        defaultContext = undefined;
        requestDefaultContext(); // Regenerate default context
    }
}

/**
 * Register a context for the given directory (specified as a URI).
 *
 * Pass `isolated: true` for canister entrypoints that need their own moc.js
 * instance (e.g. for per-canister `--enhanced-migration` flags), since
 * `setExtraFlags` does not reset all flags between calls.
 */
export async function addContext(
    uri: string,
    version?: Version,
    workspaceRoot?: string,
    isolated = false,
): Promise<Context> {
    const existing = contexts.find((other) => uri === other.uri);
    if (existing) {
        console.warn('Duplicate contexts for URI:', uri);
        return existing;
    }
    const [motoko, mocJsInfo] = await requestMotokoInstance(
        uri,
        version,
        workspaceRoot || '',
        isolated,
    );
    const context = new Context(uri, motoko, mocJsInfo);
    insertContext(context);
    return context;
}

let isolatedCompilerCounter = 0;

/** Load `moc.js` with a fresh module scope, bypassing the require cache. */
function loadFreshCompiler(mocJsPath: string): any {
    if (!existsSync(mocJsPath)) {
        throw new Error(
            `Cannot create isolated moc.js context: ${mocJsPath} not found. ` +
                `Run 'npm run prepare:moc-bundled' to install it.`,
        );
    }
    const code = readFileSync(mocJsPath, 'utf8');
    const m = new Module(`${mocJsPath}#${++isolatedCompilerCounter}`) as any;
    m.paths = (Module as any)._nodeModulePaths(dirname(mocJsPath));
    m._compile(code, mocJsPath);
    if (!m.exports.Motoko) {
        throw new Error(
            `Invalid moc.js at ${mocJsPath}: missing Motoko export`,
        );
    }
    return m.exports.Motoko;
}

/**
 * Inserts a context object into the global contexts array, maintaining order.
 * The order is determined first by URI length (shorter URIs come later),
 * then lexicographically by URI if lengths are equal.
 *
 * @param context - The context object to insert.
 */
function insertContext(context: Context) {
    let index = 0;
    const uri = context.uri;
    while (index < contexts.length) {
        const other = contexts[index];
        if (
            uri.length > other.uri.length ||
            (uri.length === other.uri.length &&
                uri.localeCompare(other.uri) < 0)
        ) {
            break;
        }
        index++;
    }
    contexts.splice(index, 0, context);
}

/**
 * Return all currently active contexts.
 */
export function allContexts(): Context[] {
    return contexts;
}

/**
 * Find the most relevant context for the given URI.
 */
export function getContext(uri: string): Context {
    const context = contexts.find((context) => uri.startsWith(context.uri));
    if (context) {
        return context;
    }
    console.warn('Unknown context for URI:', uri);
    return requestDefaultContext();
}

/**
 * Check if a context is available for the given URI.
 */
export function hasContext(uri: string): boolean {
    return contexts.some((context) => uri.startsWith(context.uri));
}
